sudo: false
language: python
env: RUNNER=travis
python:
  - "3.4"
before_install:
  - '[ -d .downloads ] || mkdir .downloads'
  - (cd .downloads; [ -d prince-10r3-linux-generic-x86_64 ] || curl -s http://www.princexml.com/download/prince-10r3-linux-generic-x86_64.tar.gz | tar xzf -)
  - echo $PWD/.prince | ./.downloads/prince-10r3-linux-generic-x86_64/install.sh
  - export PATH=$PWD/.prince/bin:$PATH
  - prince --version
  - cd web; bundle install
  - pip install --upgrade pip
  - psql -c 'create database sectors;' -U postgres
install: pip install -r requirements/local.txt --download-cache $HOME/.pip-cache --upgrade
script:
  - ./build.sh
  - ./test.sh
cache:
  directories:
    - /home/travis/virtualenv
    - $HOME/.pip-cache/
